// <auto-generated />
using System;
using EMS_SYSTEM.APPLICATION;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS_SYSTEM.APPLICATION.Migrations
{
    [DbContext(typeof(UnvcenteralDataBaseContext))]
    [Migration("20240423235334_addIdentityClasses")]
    partial class addIdentityClasses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.AcadYead", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("ACAD_YEAD", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.Assess", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.ToTable("ASSESS", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.Bylaw", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("CodeStudyMethodId")
                        .HasColumnType("int")
                        .HasColumnName("CODE_STUDY_METHOD_ID");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("FACULTY_ID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("CodeStudyMethodId");

                    b.HasIndex("FacultyId");

                    b.ToTable("BYLAW", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("FacultyAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FACULTY_ADDRESS");

                    b.Property<string>("FacultyCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FACULTY_CODE");

                    b.Property<string>("FacultyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FACULTY_NAME");

                    b.Property<int?>("FacultyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FACULTY_TYPE_ID");

                    b.HasKey("Id");

                    b.HasIndex("FacultyTypeId");

                    b.ToTable("FACULTY", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultyHieryical", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("BylawId")
                        .HasColumnType("int")
                        .HasColumnName("BYLAW_ID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<int?>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ORDER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("PARENT_ID");

                    b.Property<int?>("PhaseId")
                        .HasColumnType("int")
                        .HasColumnName("PHASE_ID");

                    b.Property<int?>("SemeterId")
                        .HasColumnType("int")
                        .HasColumnName("SEMETER_ID");

                    b.HasKey("Id");

                    b.HasIndex("BylawId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("SemeterId");

                    b.ToTable("FACULTY_HIERYICAL", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultyNode", b =>
                {
                    b.Property<int>("FacultyNodeId")
                        .HasColumnType("int")
                        .HasColumnName("FACULTY_NODE_ID");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODE");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("FACULTY_ID");

                    b.Property<int?>("Level")
                        .HasColumnType("int")
                        .HasColumnName("LEVEL");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<int?>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ORDER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("PARENT_ID");

                    b.HasKey("FacultyNodeId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("ParentId");

                    b.ToTable("FACULTY__NODES", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultyPhase", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODE");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("FACULTY_ID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<int?>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ORDER");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("FACULTY_PHASES", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultySemester", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODE");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("FACULTY_ID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<int?>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ORDER");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("FACULTY_SEMESTER", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultyType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("FACULTY_TYPE", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ADDRESS");

                    b.Property<int?>("Cityid")
                        .HasColumnType("int")
                        .HasColumnName("CITYID");

                    b.Property<DateOnly?>("Dateofbrith")
                        .HasColumnType("date")
                        .HasColumnName("DATEOFBRITH");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<int?>("Facultyid")
                        .HasColumnType("int")
                        .HasColumnName("FACULTYID");

                    b.Property<int?>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("GENDER");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MOBILE");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("Nationalid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NATIONALID");

                    b.HasKey("Id");

                    b.HasIndex("Facultyid");

                    b.ToTable("STUDENTS", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.StudentSemester", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("AcadYearId")
                        .HasColumnType("int")
                        .HasColumnName("ACAD_YEAR_ID");

                    b.Property<int?>("FacultyHieryicalId")
                        .HasColumnType("int")
                        .HasColumnName("FACULTY_HIERYICAL_ID");

                    b.Property<int?>("FacultyNodeId")
                        .HasColumnType("int")
                        .HasColumnName("FACULTY_NODE_ID");

                    b.Property<decimal?>("Gpa")
                        .HasColumnType("decimal(5, 3)")
                        .HasColumnName("GPA");

                    b.Property<int?>("IsPass")
                        .HasColumnType("int")
                        .HasColumnName("IS_PASS");

                    b.Property<decimal?>("Precentage")
                        .HasColumnType("decimal(5, 3)")
                        .HasColumnName("PRECENTAGE");

                    b.Property<int?>("StuentId")
                        .HasColumnType("int")
                        .HasColumnName("STUENT_ID");

                    b.Property<int?>("StuentSatutsId")
                        .HasColumnType("int")
                        .HasColumnName("STUENT_SATUTS_ID");

                    b.Property<decimal?>("Toal")
                        .HasColumnType("decimal(8, 3)")
                        .HasColumnName("TOAL");

                    b.HasKey("Id");

                    b.HasIndex("AcadYearId");

                    b.HasIndex("FacultyHieryicalId");

                    b.HasIndex("FacultyNodeId");

                    b.HasIndex("StuentId");

                    b.ToTable("STUDENT_SEMESTERS", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.StudeyMethod", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("STUDEY_METHOD", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.StuentSatut", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("StuentSatuts")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STUENT_SATUTS");

                    b.ToTable("STUENT_SATUTS", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("CreditHours")
                        .HasColumnType("int")
                        .HasColumnName("CREDIT_HOURS");

                    b.Property<int?>("FacultyHieryicalId")
                        .HasColumnType("int")
                        .HasColumnName("FACULTY_HIERYICAL_ID");

                    b.Property<int?>("FacultyPhasesId")
                        .HasColumnType("int")
                        .HasColumnName("FACULTY_PHASES_ID");

                    b.Property<int?>("FacultySemesterId")
                        .HasColumnType("int")
                        .HasColumnName("FACULTY_SEMESTER_ID");

                    b.Property<int?>("MaxDegree")
                        .HasColumnType("int")
                        .HasColumnName("MAX_DEGREE");

                    b.Property<int?>("MinDegree")
                        .HasColumnType("int")
                        .HasColumnName("MIN_DEGREE");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("FacultyPhasesId");

                    b.ToTable("SUBJECTS", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.SubjectAssess", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("MaxDegree")
                        .HasColumnType("int")
                        .HasColumnName("MAX_DEGREE");

                    b.Property<int?>("MinDegree")
                        .HasColumnType("int")
                        .HasColumnName("MIN_DEGREE");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SUBJECT_ID");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("SUBJECT_ASSESS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.Bylaw", b =>
                {
                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.StudeyMethod", "CodeStudyMethod")
                        .WithMany("Bylaws")
                        .HasForeignKey("CodeStudyMethodId")
                        .HasConstraintName("FK_BYLAW_STUDEY_METHOD");

                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.Faculty", "Faculty")
                        .WithMany("Bylaws")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK_BYLAW_FACULTY");

                    b.Navigation("CodeStudyMethod");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.Faculty", b =>
                {
                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.FacultyType", "FacultyType")
                        .WithMany("Faculties")
                        .HasForeignKey("FacultyTypeId")
                        .HasConstraintName("FK_FACULTY_FACULTY_TYPE");

                    b.Navigation("FacultyType");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultyHieryical", b =>
                {
                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.Bylaw", "Bylaw")
                        .WithMany("FacultyHieryicals")
                        .HasForeignKey("BylawId")
                        .HasConstraintName("FK_FACULTY_HIERYICAL_BYLAW");

                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.FacultyPhase", "Phase")
                        .WithMany("FacultyHieryicals")
                        .HasForeignKey("PhaseId")
                        .HasConstraintName("FK_FACULTY_HIERYICAL_FACULTY_PHASES");

                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.FacultySemester", "Semeter")
                        .WithMany("FacultyHieryicals")
                        .HasForeignKey("SemeterId")
                        .HasConstraintName("FK_FACULTY_HIERYICAL_FACULTY_SEMESTER");

                    b.Navigation("Bylaw");

                    b.Navigation("Phase");

                    b.Navigation("Semeter");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultyNode", b =>
                {
                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.Faculty", "Faculty")
                        .WithMany("FacultyNodes")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK_FACULTY__NODES_FACULTY");

                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.FacultyNode", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_FACULTY__NODES_FACULTY__NODES");

                    b.Navigation("Faculty");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultyPhase", b =>
                {
                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.Faculty", "Faculty")
                        .WithMany("FacultyPhases")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK_FACULTY_PHASES_FACULTY");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultySemester", b =>
                {
                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.Faculty", "Faculty")
                        .WithMany("FacultySemesters")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK_FACULTY_SEMESTER_FACULTY");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.Student", b =>
                {
                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("Facultyid")
                        .HasConstraintName("FK_STUDENTS_FACULTY");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.StudentSemester", b =>
                {
                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.AcadYead", "AcadYear")
                        .WithMany("StudentSemesters")
                        .HasForeignKey("AcadYearId")
                        .HasConstraintName("FK_STUDENT_SEMESTERS_ACAD_YEAD");

                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.FacultyHieryical", "FacultyHieryical")
                        .WithMany("StudentSemesters")
                        .HasForeignKey("FacultyHieryicalId")
                        .HasConstraintName("FK_STUDENT_SEMESTERS_STUDENT_SEMESTERS");

                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.FacultyNode", "FacultyNode")
                        .WithMany("StudentSemesters")
                        .HasForeignKey("FacultyNodeId")
                        .HasConstraintName("FK_STUDENT_SEMESTERS_FACULTY__NODES");

                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.Student", "Stuent")
                        .WithMany("StudentSemesters")
                        .HasForeignKey("StuentId")
                        .HasConstraintName("FK_STUDENT_SEMESTERS_STUDENTS");

                    b.Navigation("AcadYear");

                    b.Navigation("FacultyHieryical");

                    b.Navigation("FacultyNode");

                    b.Navigation("Stuent");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.Subject", b =>
                {
                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.FacultyPhase", "FacultyPhases")
                        .WithMany("Subjects")
                        .HasForeignKey("FacultyPhasesId")
                        .HasConstraintName("FK_SUBJECTS_FACULTY_PHASES");

                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.FacultySemester", "IdNavigation")
                        .WithOne("Subject")
                        .HasForeignKey("EMS_SYSTEM.DOMAIN.Models.Subject", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_SUBJECTS_FACULTY_SEMESTER");

                    b.Navigation("FacultyPhases");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.SubjectAssess", b =>
                {
                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.Subject", "Subject")
                        .WithMany("SubjectAssesses")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK_SUBJECT_ASSESS_SUBJECTS");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EMS_SYSTEM.DOMAIN.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.AcadYead", b =>
                {
                    b.Navigation("StudentSemesters");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.Bylaw", b =>
                {
                    b.Navigation("FacultyHieryicals");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.Faculty", b =>
                {
                    b.Navigation("Bylaws");

                    b.Navigation("FacultyNodes");

                    b.Navigation("FacultyPhases");

                    b.Navigation("FacultySemesters");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultyHieryical", b =>
                {
                    b.Navigation("StudentSemesters");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultyNode", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("StudentSemesters");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultyPhase", b =>
                {
                    b.Navigation("FacultyHieryicals");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultySemester", b =>
                {
                    b.Navigation("FacultyHieryicals");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.FacultyType", b =>
                {
                    b.Navigation("Faculties");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.Student", b =>
                {
                    b.Navigation("StudentSemesters");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.StudeyMethod", b =>
                {
                    b.Navigation("Bylaws");
                });

            modelBuilder.Entity("EMS_SYSTEM.DOMAIN.Models.Subject", b =>
                {
                    b.Navigation("SubjectAssesses");
                });
#pragma warning restore 612, 618
        }
    }
}
